version: "3.7"

services:
  https:
    image: ghcr.io/sireto/custom-domain:latest
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "127.0.0.1:9000:9000"
    restart: unless-stopped
    networks:
      - frontend
    env_file:
      - .env
    volumes:
      - https_domains:/app/domains
      - https_data:/var/lib/custom-domain
      - https_db:/app/data

volumes:
  https_data:
    external: true
  https_domains:
    external: true
  https_db:
    external: true

networks:
  frontend:
