#!/usr/bin/env bash
# Installs Custom Domain on a fresh Ubuntu 22.04/24.04 or Debian 12 server:
# Docker Engine, the production Compose layout under /opt/custom-domain,
# a generated configuration with fresh secrets, the firewall, and a
# `custom-domain` command on the host. Safe to run again: existing
# configuration and data are kept.
#
# Settings (environment variables, or /etc/custom-domain-install.env):
#   ACME_EMAIL              contact for the certificate authority (recommended)
#   CUSTOM_DOMAIN_VERSION   release to install: the image tag and, unless overridden, the
#                           git tag the Compose file is fetched from (default: latest,
#                           which follows main; production pins a version such as 0.3.1)
#   CUSTOM_DOMAIN_REF       git ref to fetch deploy files from instead (default: the
#                           version, or main when the version is latest)
#   CUSTOM_DOMAIN_DIR       install directory (default: /opt/custom-domain)
#   CUSTOM_DOMAIN_SOURCE    local checkout to copy deploy files from instead of downloading
#   SKIP_FIREWALL=1         do not touch ufw (when the provider firewall is used instead)
#   SKIP_DOCKER_INSTALL=1   Docker is already installed and running
set -euo pipefail

if [ -f /etc/custom-domain-install.env ]; then
    set -a
    # shellcheck disable=SC1091
    . /etc/custom-domain-install.env
    set +a
fi

VERSION="${CUSTOM_DOMAIN_VERSION:-latest}"
if [ -n "${CUSTOM_DOMAIN_REF:-}" ]; then
    REF="${CUSTOM_DOMAIN_REF}"
elif [ "${VERSION}" = "latest" ]; then
    REF="main"
else
    REF="${VERSION}"   # release tags are plain versions
fi
DIR="${CUSTOM_DOMAIN_DIR:-/opt/custom-domain}"
SOURCE="${CUSTOM_DOMAIN_SOURCE:-}"
RAW="https://raw.githubusercontent.com/sireto/custom-domain/${REF}"
IMAGE="ghcr.io/sireto/custom-domain:${VERSION}"
COMPOSE="docker compose -f ${DIR}/deploy/compose.production.yml"

log() { printf '\n==> %s\n' "$*"; }

if [ "$(id -u)" -ne 0 ]; then
    echo "run as root (sudo)" >&2
    exit 1
fi

# --- Docker ------------------------------------------------------------------
if [ "${SKIP_DOCKER_INSTALL:-0}" != "1" ] && ! command -v docker >/dev/null 2>&1; then
    log "Installing Docker Engine"
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -qq
    apt-get install -y -qq ca-certificates curl gnupg >/dev/null
    install -m 0755 -d /etc/apt/keyrings
    # shellcheck disable=SC1091
    . /etc/os-release
    curl -fsSL "https://download.docker.com/linux/${ID}/gpg" -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
https://download.docker.com/linux/${ID} ${VERSION_CODENAME} stable" \
        >/etc/apt/sources.list.d/docker.list
    apt-get update -qq
    apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin >/dev/null
    systemctl enable --now docker >/dev/null 2>&1 || true
fi
docker compose version >/dev/null 2>&1 || { echo "docker compose plugin missing" >&2; exit 1; }

# --- Firewall ----------------------------------------------------------------
if [ "${SKIP_FIREWALL:-0}" != "1" ] && command -v ufw >/dev/null 2>&1; then
    log "Opening SSH, HTTP and HTTPS in ufw"
    ufw allow OpenSSH >/dev/null
    ufw allow 80/tcp >/dev/null
    ufw allow 443/tcp >/dev/null
    ufw allow 443/udp >/dev/null
    ufw --force enable >/dev/null
fi

# --- Files -------------------------------------------------------------------
log "Preparing ${DIR}"
mkdir -p "${DIR}/deploy"
if [ ! -f "${DIR}/deploy/compose.production.yml" ]; then
    if [ -n "${SOURCE}" ]; then
        cp "${SOURCE}/deploy/compose.production.yml" "${DIR}/deploy/"
    else
        curl -fsSL "${RAW}/deploy/compose.production.yml" -o "${DIR}/deploy/compose.production.yml"
    fi
fi

secret() { openssl rand -hex "$1"; }
if [ ! -f "${DIR}/deploy/.env" ]; then
    log "Generating configuration and secrets"
    pg_password="$(secret 24)"
    umask 077
    cat >"${DIR}/deploy/.env" <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Keep this file private.
DATABASE_URL=postgresql+psycopg://custom_domain:${pg_password}@db:5432/custom_domain
POSTGRES_PASSWORD=${pg_password}
ACME_EMAIL=${ACME_EMAIL:-}
EDGE_ASSERTION_KEYS=1:$(secret 32)
EDGE_TOKEN=$(secret 24)
PORTAL_PASSWORD=$(secret 16)
CADDY_REDIS_PASSWORD=$(secret 24)
CADDY_REDIS_ENCRYPTION_KEY=$(secret 32)
CUSTOM_DOMAIN_IMAGE=${IMAGE}
EOF
    umask 022
else
    log "Keeping existing ${DIR}/deploy/.env"
fi

# A host command that runs the operator CLI inside the API container.
cat >/usr/local/bin/custom-domain <<EOF
#!/usr/bin/env bash
# Runs the Custom Domain operator CLI inside the API container.
exec ${COMPOSE} exec api custom-domain "\$@"
EOF
chmod 0755 /usr/local/bin/custom-domain

# --- Start -------------------------------------------------------------------
log "Pulling ${IMAGE} and starting the stack"
cd "${DIR}/deploy"
${COMPOSE} pull -q
${COMPOSE} up -d --wait --wait-timeout 300

# --- Summary -----------------------------------------------------------------
ip4="$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for (i=1;i<=NF;i++) if ($i=="src") print $(i+1)}' | head -1 || true)"
ip6="$(ip -6 route get 2606:4700:4700::1111 2>/dev/null | awk '{for (i=1;i<=NF;i++) if ($i=="src") print $(i+1)}' | head -1 || true)"
cat <<EOF

Custom Domain is running.

  Install directory:  ${DIR}
  Configuration:      ${DIR}/deploy/.env   (secrets; back it up)
  Image:              ${IMAGE}
  This server:        ${ip4:-?}${ip6:+  ${ip6}}

Next steps
  1. Create a DNS record for the name customers will CNAME to (for example
     edge.example.net): A ${ip4:-<ipv4>}${ip6:+ and AAAA ${ip6}}.
  2. Check the deployment:        custom-domain doctor
     or open the portal from your machine through an SSH tunnel:
       ssh -N -L 9000:127.0.0.1:9000 root@${ip4:-<server>}   then   http://localhost:9000/portal
     (password: PORTAL_PASSWORD in ${DIR}/deploy/.env)
  3. Create an application:       custom-domain application create --slug acme --name "Acme" --cname-target edge.example.net
     register its origin:         custom-domain origin register --application acme --host app.acme.example --scheme https --port 443
     verify and activate it:      custom-domain origin verify --application acme --host app.acme.example --activate
     issue a credential:          custom-domain credential issue --application acme --label backend
  4. Read docs/deployment.md for backups, monitoring and upgrades
     (upgrade: edit CUSTOM_DOMAIN_IMAGE in .env, then
      ${COMPOSE} pull && ${COMPOSE} up -d).

The management API (port 9000) is reachable only inside the Docker network:
operate it with the custom-domain command above, or publish it through an
authenticated reverse proxy of your own if applications must call it from
elsewhere (docs/deployment.md).
EOF
